FROM node:24

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies (Linux-compatible)
RUN npm install --legacy-peer-deps --no-audit

EXPOSE 8081

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

